name: gmx-scripts
channels:
  - conda-forge
  - defaults
dependencies:
  - ambertools=23.6
  - openbabel=3.1.1
  - python=3.12.2
  - pip:
      - acpype==2023.10.27
      - alchemlyb==2.4.1
      - ipykernel
      - py3dmol
      - rdkit==2024.3.5
